### PR TITLE
Moved to lab and "standard" test structure

### PR DESCRIPTION
**Pull request by marcopiraccini**
Seneca must be inited externally wiith the transport to be tested.  Example:
```
describe('transport', function() {

  shared.basictest({
    seneca: get_seneca(),
    script: lab,
    type: 'tcp'
  })
(...)
```

### CODE REVIEW

**Comment by geek** [comment]
@marcopiraccini please add a `.travis.yml` file as well, this looks like the reason why the PR is failing on travis

**Comment by geek** [comment]
@marcopiraccini are there plans to update seneca-transport tests as well?  With this PR seneca-transport tests fail with the following errors:

```
  1) transport happy-tcp:
     TypeError: test.foo_test is not a function

  2) transport happy-pin-tcp:
     TypeError: test.foo_pintest is not a function

  3) transport happy-web:
     TypeError: test.foo_test is not a function

  4) transport happy-pin-web:
     TypeError: test.foo_pintest is not a function
```

**Comment by marcopiraccini** [comment]
Yes, indeed I used seneca-trasport for testing it. See this fork: https://github.com/marcopiraccini/seneca-transport

**Comment by geek** [comment]
LTGM

**Pull request merged**
